### ISSUE TITLE
Password hashing

### ISSUE THREAD

**Issue by artbot345** [OpusDevelopment/Website#1]
Replace all instances of md5 with sha512 + salt for password hashing.

**Comment by astenbal** [comment]
I know, I'd prefer to not make the actual full encryption available on here though, so on the actual server the encryption will be different from what is on here :)

**Comment by artbot345** [comment]
Not relevant if we use SHA512 with a long salt.
We also need to sanitize ALL user input.

**Comment by astenbal** [comment]
Should be done now :)
